var quotes = [
	{"id":0, "quote":"One person's annoying is another's inspiring and heroic."},
	{"id":1, "quote":"I stand behind my decision to avoid salad and other disgusting things."},
	{"id":2, "quote":"The thing about youth culture is I don't understand it."},
 	{"id":3, "quote":"You're pretty cocky for someone who's job is obsolete because of the Internet."},
 	{"id":4, "quote":"I don't know what it is about big, outdoor gatherings that makes everyone wanna urinate all over everything. But it does, and they do."},
 	{"id":5, "quote":"But sometimes if I don't push you in the right direction, you end up standing still."},
 	{"id":6, "quote":"You know what I would do, you should make a pros and cons list, that always works for me."},
 	{"id":7, "quote":"Yesterday I was tough & direct. Today I have to be charming. Basically yesterday I was Hilary Clinton, and today I’m Bill."},
 	{"id":8, "quote":"I am big enough to admit I am often inspired by myself."},
 	{"id":9, "quote":"I'm gonna be direct and honest with you, I would like a glass of red wine and I'll take the cheapest one you have because I can't tell the difference."},
 	{"id":10, "quote":"Tom, it's perfectly normal to feel devastated when something is over. That's exactly how I felt when that Planet Earth series ended."},
 	{"id":11, "quote":"What I hear when I'm being yelled at is people caring loudly at me."},
 	{"id":12, "quote":"I always carry emergency s'more rations in my car."},
 	{"id":13, "quote":"Now if you'll excuse me, I'm about to endorse 10 beers into my mouth, cause this has been an incredibly stressful evening."},
 	{"id":14, "quote":"I took your idea and made it better."},
 	{"id":15, "quote":"If you would be willing to just take a brief pit stop, we could see Indiana's second-largest rocking chair."},
 	{"id":16, "quote":"Andy, pack up our bananas."},
 	{"id":17, "quote":"Hey Leslie. It's Leslie. Hang in there. I love you. Bye."},
 	{"id":18, "quote":"Don't touch my pickles, Ann!"},
 	{"id":19, "quote":"I think this is going to be a good bonding experience with Ron. Guys love it when you can show them you're better than they are at something they love."},
 	{"id":20, "quote":"Why would anybody ever eat anything besides breakfast food?"},
 	{"id":21, "quote":"You are a beautiful, talented, brilliant, powerful muskox."},
 	{"id":22, "quote":"I don't want to be over dramatic, but today felt like a hundred years in hell and the absolute worst day of my life."},
 	{"id":23, "quote":"Organizing my agenda. Wait, that doesn't sound fun... jammin' on my planner!"},
 	{"id":24, "quote":"I need to ascertain the whereabouts of some oversize ceremonial scissors."},
 	{"id":25, "quote":"Ron, your mustache fell off!"},
 	{"id":26, "quote":"It's the end of the world as they know it, but Pawnee feels fine."},
 	{"id":27, "quote":"Pawnee, first in friendship, fourth in obesity."},
 	{"id":28, "quote":"Absotootely I am, very sorry I just used that word."},
 	{"id":29, "quote":"No matter what I do, literally nothing bad can happen to me. I'm like a white male US senator."},
 	{"id":30, "quote":"I've taught them too well, I've created a mob of little Leslie Knope monsters."},
 	{"id":31, "quote":"No I can't go home. I have to get ready for the chamber of secrets."},
 	{"id":32, "quote":"Positive is always better than negative."},
 	{"id":33, "quote":"The raccoon problem is under control. They have their part of the town and we have ours."},
 	{"id":34, "quote":"My strategy is to win."},
 	{"id":35, "quote":"I'm gonna get drunk, and then I'm going to order a 3 course meal where each course is made of dessert."},
 	{"id":36, "quote":"That's why people respect Hillary Clinton so much, 'cause nobody takes a punch like her."},
 	{"id":37, "quote":"There aint no party like a Leslie Knope party."},
 	{"id":38, "quote":"Oh Ann, you beautiful rule-breaking moth."},
 	{"id":39, "quote":"I just slept seven hours, which is twice as long as I normally sleep, so I'm a little disoriented."},
 	{"id":40, "quote":"From time to time when I think of an eloquent saying or phrase, I have Tom write them down. He's collecting them for my memoirs."},
 	{"id":41, "quote":"Careful! The floor and the wall just switched."},
 	{"id":42, "quote":"God, I am so annoyed that he would hypothetically do that."},

];
